# Configuration options for your blog - customise to taste
# This file contains no secret information, so can be stored in source control (unlike database.yml)
title: o2h blog
url:   http://blog.o2h.cz
author:
  name:    Michal Cichra        # For copyright notice and ATOM feeds
  email:   m@o2h.cz # Exception emails will go here, and it is used in ATOM feeds
